services:
  AnilistLink:
    image: dogberttech/anilist-link:latest
    # To build locally instead: comment out image above and uncomment below
    # build: .
    container_name: AnilistLink
    restart: unless-stopped
    shm_size: "2g"
    volumes:
      - ./config:/config
      - ./media/anime:/media/anime
    environment:
      - PUID=99
      - PGID=100
      - UMASK=002
      - TZ=America/New_York
      - DEBUG=false
    ports:
      - "9876:9876"
